### ISSUE TITLE
run bundle install

### ISSUE THREAD

**Issue by GoulartJnr** [Code4SA/dashboard#14]
Sorry, I'm new to this. Where I run the command "run bundle install"?

**Comment by longhotsummer** [comment]
This is a Ruby-based web app. You'll need to ensure you have Ruby and [Bundler](http://bundler.io/) installed. Then, running `bundler install` is how you tell ruby to install the dependencies for the project. There are lots of tutorials or setting up bundler and ruby in case you get stuck.

**Comment by GoulartJnr** [comment]
Ah, ok, thank you! I will do that.
